version: "3"
services:
  app:
    build:
      context: .
    container_name: book_app
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    env_file:
      - compose.env

  db:
    image: postgres
    ports:
      - "5432"
