version: "3"
services:
  app:
    build:
      context: .
    container_name: app
    links:
      - db
    ports:
      - "8080:8080"
    env_file:
      - compose.env

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

